import json
import re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
out = root / 'graphify-out'
batches = json.loads((out / 'semantic-batches.json').read_text())
# Each row is an explicitly observed source concept: label | evidence anchor | factual description.
rows = [
[
['Bug report|name: Bug Report|Template requires observed behavior and reproduction steps.', 'Extension exclusion|pi -ne|Core bug reporters first validate with extensions disabled.', 'Contribution quality bar|CONTRIBUTING.md|New contributor issues are auto-closed and reviewed by maintainers.'],
['Discord questions|contact_links|Questions are directed to Discord.', 'Disabled blank issues|blank_issues_enabled|Only configured issue templates can be submitted.'],
['Contribution proposal|name: Contribution Proposal|New contributors propose the what and why before submitting a PR.', 'Maintainer review|auto-closed|Auto-closed proposals are reviewed against CONTRIBUTING.md.'],
['Package reports|name: Package Report|Reports concern packages listed on pi.dev.', 'Unsafe package behavior|Malicious or unsafe behavior|Report categories include malicious behavior, impersonation and trademark violations.'],
['Contributor approval|name: Approve Contributor|Maintainer comments update approved contributor capabilities.', 'lgtmi|lgtmi|Approves future issues only.', 'lgtm|lgtm|Approves future PR participation.', 'APPROVED_CONTRIBUTORS|APPROVED_FILE|Persistent approval records hold issue or pr capabilities.'],
['Release binaries|name: Build Binaries|Tag-driven workflow produces multi-platform binary and source artifacts.', 'Source archive|Create source archive|Binary builds use a release source archive.', 'Draft release staging|draft release|Public release publication follows staged artifacts and later publishing jobs.', 'npm publishing|node scripts/publish.mjs|Workflow invokes package publication after checks.'],
['CI validation|name: CI|Main pushes and pull requests build, check, and test.', 'MCP conformance|mcp-conformance|Source MCP client is checked against a pinned official suite and baseline.'],
['Issue analysis|name: Issue Analysis|Authorized labels or staff comments trigger issue analysis with the repository is prompt.', 'pi-analyze|ANALYZE_LABEL|Label trigger runs on the default Linux runner.', 'Runner profiles|RUNNER_PROFILES|Hardcoded profiles support Linux, Windows and macOS.', 'Dedicated OAuth state|rotates refresh tokens|Workflow uses dedicated credentials because refresh token rotation prevents shared state.'],
['Issue gate|name: Issue Gate|New issues require collaborator or contributor approval.', 'Issue capability|capability ===|Issue and pr capabilities both permit future issues.', 'untriaged|untriaged|Rejected submissions are labeled and closed as not planned.'],
['Triage labels|name: Issue Triage Labels|Reopen and label events maintain issue triage state.', 'last-read|LAST_READ_LABEL|Last-read advances a triage range through issue numbers.', 'no-action|NO_ACTION_LABEL|Untriaged issues in a completed range are closed unless marked to-discuss.'],
['Nix release packaging|name: Nix|Workflow builds a pinned model catalogue flake and advances stable for releases.', 'Model catalogue pin|nix/model-catalog.json|Main pin is refreshed when stale; tags keep their committed pin.', 'Stable fast-forward|Fast-forward stable|Stable advances after successful tagged builds.'],
['Production dependency audit|name: npm audit|Scheduled workflow audits production dependencies.', 'Registry signatures|Verify registry signatures|npm audit signatures verifies production registry signatures.', 'Disabled lifecycle scripts|npm ci --ignore-scripts|Dependency installation omits package lifecycle scripts.'],
['PR gate|name: PR Gate|New pull requests are closed unless the author is trusted or approved.', 'PR capability|capability ===|Only pr capability admits ordinary approved PR authors.', 'Trusted bots|TRUSTED_BOT_AUTHORS|Specified bot accounts bypass the contributor gate.'],
['Model catalogue publication|name: Publish Model Catalog|Workflow generates, validates and optionally publishes catalog JSON.', 'R2 catalogue upload|Publish model catalog to R2|Generated artifacts are uploaded to the production R2 bucket.', 'Publication window|Check publication window|Automatic publication follows Europe/Vienna weekday windows.'],
['Issue close cleanup|name: Remove In Progress|Closed issue events remove inprogress when present.', 'inprogress|labelName|Label is removed through the GitHub issues API.'],
['Release changelog audit|Audit changelog|Reviews all commits since the latest release against package changelogs.', 'Cross-package duplication|Cross-package duplication rule|End-user changes in ai, agent or tui also belong in the coding-agent changelog.', 'Unreleased changes|Unreleased|Audit operates on unreleased sections and documented attribution formats.'],
['Behavior-preserving simplification|Review the completed|Simplifies an affected workpackage while preserving intended behavior.', 'Trust-boundary validation|trust boundaries|Relies on established internal types while validating external inputs.', 'Significant removal approval|Approval gate|Requires explicit approval before changing deliberate features or interfaces.'],
['Issue investigation|Analyze GitHub issue|Independently verifies bugs or feature requests without implementing.', 'Root cause tracing|Trace the code path|Bug analysis derives root causes from code and execution paths.', 'CI analysis behavior|CI=true|CI omits local inprogress labeling and assignment.'],
['PR review|Review PRs|Reviews PR metadata, related issues, diffs and documentation requirements.', 'Branch-preserving review|without checking out|Uses diff and local/fetched content without switching the working tree.', 'Contributor changelog policy|contributor PRs|Contributor PRs must not edit changelogs.'],
['Security advisory drafting|Update a GitHub security advisory|Investigates affected ranges and prepares a publication-ready advisory.', 'CVSS confirmation|CVSS|Original and proposed scores are recorded and reviewed.', 'CVE request gate|request_cve|CVE request requires explicit approval or a true draft flag.', 'Private advisory comment limitation|does not expose|Public documented APIs do not expose advisory discussion.'],
['Task completion prompt|Wrap it.|Finishes authorized work with changelog, concrete final comment, commit and push.', 'Session-only staging|Commit only files|Stages only files changed in the current session.', 'Issue completion events|explicitly close|Explicit issue closing emits the workflows needed for cleanup.'],
['Provider integration checklist|Adding a New LLM Provider|Coordinates types, streaming implementation, catalogs, tests and coding-agent wiring.', 'Lazy registration|Lazy Registration|Provider implementation modules are loaded through lazy wrappers.', 'Provider test matrix|Tests|Checklist includes streaming, overflow, handoff and tool-result scenarios.'],
],
[
['Controlled TUI testing|Testing pi Interactive|Uses a controlled tmux terminal for interactive behavior checks.', 'Release smoke test|For release smoke tests|Node and Bun release binaries require an actual model reply from outside the repository.'],
['Lockstep releases|Lockstep versioning|All packages share one version; patch includes fixes/additions and minor breaking changes.', 'GitHub OIDC publishing|trusted publishing|Tag workflows publish npm packages through OIDC.', 'Nix stable release|CI builds the Nix release|Stable is advanced only after tagged flake builds.', 'Release recovery|If CI publish|Failed publication is retried without recreating the release version.'],
['Development invariants|Code Quality|Repository rules favor concrete TypeScript types, explicit imports and erasable syntax.', 'Install security|Dependency and Install Security|Dependencies are pinned and lifecycle scripts disabled by default.', 'Session-safe Git|Multiple pi sessions|Only current-session files are staged and destructive shared-tree commands are prohibited.', 'Targeted verification|Commands|Code changes require check; build and full tests require explicit requests.'],
['Minimal extensible core|pi\'s core is minimal|Features outside the core belong in extensions to avoid maintenance bloat.', 'Contribution gate|Contribution Gate|New issues and PRs are auto-closed until maintainer approval.', 'Human maintainer review|Human review remains|AI assistance cannot replace final maintainer decisions.', 'Code understanding|You must understand your code|Contributors must explain their changes and interactions.'],
['Pi agent harness|minimal, extensible agent harness|Pi coordinates customizable local agent workflows.', 'Pi packages|Pi packages|Extensions, skills, prompts and themes are distributed through npm or git.', 'CLI and SDK interfaces|Pi TypeScript SDK|Interactive, print, JSON, RPC and SDK interfaces serve different hosts.', 'Pinned installer|installer pins|Managed installer pins dependencies and is updated through pi update.'],
['Local-user trust boundary|security boundary|Pi operates with the local user account permissions.', 'Trusted executable resources|trustworthy extensions|Extensions, skills and repositories must be trusted.', 'Private vulnerability reporting|Reporting a Vulnerability|Security reports go to private channels.', 'Prompt injection scope|Prompt injection attacks|Expected prompt-injection and trusted-local-write behavior are out of scope.'],
['Agent-core 1.0 migration|Removed the experimental harness|Agent-core now contains Agent, loop, proxy and types; durable sessions moved out.', 'Durable sessions package|pi-durable|Durable session consumers should use pi-durable.', 'finishTurn|finishTurn|Finalization hook runs before turn_end and replaces the older stopping hook.', 'prepareRequest|prepareRequest|Hook runs before every provider request.'],
['Stateful Agent|Stateful agent|Agent exposes state, tools and streamed lifecycle events on pi-ai.', 'AgentMessage|AgentMessage|Flexible application messages include LLM and custom roles.', 'convertToLlm|convertToLlm|Converts application messages into provider-supported LLM roles.', 'transformContext|transformContext|Optional transformation prunes or injects context.', 'Parallel tool ordering|assistant source order|Completion events follow tool completion while persisted results follow assistant order.'],
['Provider API evolution|samplingParamsByThinkingLevel|Changelog records sampling overrides by thinking level.', 'Anthropic inline tools|inline-tools-2026-09-15|Inline tool additions/redefinitions preserve the prompt cache.', 'Classifier catalogue|classifier models|Cloudflare Clef models were added to the classifier catalog.'],
['Unified LLM API|Unified LLM API|Pi-ai provides provider collections, auth, usage tracking and context handoff.', 'Provider collections|Provider Factories|Collections coordinate built-in and dynamic providers.', 'Tool-call streaming|Streaming Tool Calls|API exposes streamed tool calls and partial JSON.', 'Cross-provider handoff|Cross-Provider Handoffs|Persisted contexts can move across models and providers.', 'Image and classifier operations|Image Generation|Image/classifier catalogs have operation-specific capabilities.'],
['Chord standalone boundary|Dependency boundary|Chord must not depend on other Pi packages.', 'Plugin generations|Loaded generation|A generation owns loaded plugins and module resources.', 'Symmetric RPC plan|remain planned|Symmetric RPC and structural generation replacement are planned rather than stable current APIs.', 'Replicated state plan|Replicated state|Runtime replicates immutable authoritative state to consumers.'],
['Chord composition runtime|application-composition runtime|Standalone runtime composes facets, services and replicated state.', 'Facets|Facets|Separately bundled parts run in selected environments.', 'Stable service facades|stable facade|Consumers retain facade identities across provider replacement.', 'Replicated state|Replicated state|Atomic changes yield immutable values and independent stream codecs.', 'Remote service boundary|Remote service sources|Application adapters own transport while Chord validates strict JSON contracts.'],
['Chord Delta|Chord Delta|Produces immutable JSON revisions and exact ordered operation batches.', 'Ownership immutability|ownership contract|State is immutable by contract rather than freezing/copying.', 'Immutable replay|applyImmutable|Replay shares containers and preserves ordered revision semantics.', 'Draft lifecycle|change.state|Draft handles are valid only while the change remains open.'],
['Client API migration|Replaced|SessionSummary was replaced with durable SessionMetadata.', 'PiClient|PiClient|Experimental transport-neutral client exposes multi-session handles and structured errors.'],
['Transport-neutral Client|Transport-neutral client|Client routes the experimental Pi service protocol over ordered bytes.', 'Durable target address|serverId, sessionId, attachmentId|Full target address guards cross-server/session misrouting and delayed attachments.', 'Chord service bindings|Chord service bindings|Applications own typed service bindings above low-level request/subscribe primitives.', 'Explicit reconnect|It never reconnects|No automatic reconnection or request replay occurs.', 'Unix discovery|Unix discovery|Read-only discovery probes and verifies expected server identities.'],
['Codemode resource limits|MAX_OUTPUT_CHARS|Changelog records bounded output counts and RangeError failure.', 'CodemodeSandbox|CodemodeSandbox|Initial sandbox spike exposed injected tools in worker scripts.', 'Tool output typing|renderToolOutputType|Helper renders the resolved tool output type.'],
['QuickJS CodemodeSandbox|QuickJS VM|Runs model-written JavaScript in a WebAssembly VM with injected tools only.', 'Nested tool context isolation|Nested tool calls|Only script output and return values enter the LLM context.', 'Cross-execution store|Store|Host persists successful storeWrites across executions.', 'Injected globals|globals|Host functions can be exposed as VM globals.'],
['Sampling by thinking level|Sampling by thinking level|Model configuration supports per-level OpenAI-compatible sampling overrides.', 'Project MCP overrides|Project overrides for MCP servers|Project settings can selectively change user server availability/exposure.', 'MCP Client ID Metadata Documents|MCP Client ID Metadata Documents|Authorization can identify Pi by its client metadata document.', 'Tool renderers|Tool renderers for any tool|Renderer registration can draw tools absent from current registration.'],
['Pi coding agent|minimal, extensible agent harness|Coding-agent package supplies customizable local workflows.', 'Resources as Pi packages|Bundle them as|Executable and instruction resources can be bundled for distribution.', 'Process and SDK integration|Pi TypeScript SDK|Interactive/JSON/print/RPC and TypeScript embedding share the agent.'],
['CLI interface selection|All four modes|Interactive, print, JSON and RPC share agent resources but differ in lifetime and I/O.', 'Print mode|Print to stdout|One-shot mode writes final text and exits.', 'JSON event stream|Stream JSON events|One-shot mode exposes session events as JSONL.', 'RPC control|Control Pi with RPC|Long-lived process accepts correlated commands and emits events.', 'agent_settled|agent_settled|Marks end of automatic work after agent_end.'],
['Command-line invocation|Command Line|CLI selects modes, prompts, models, tools, resources and sessions.', 'Model selection options|--model|Provider/model lookup supports fuzzy patterns and thinking suffixes.', 'Session continuation|--continue|Continue opens most recent project session; resume opens selector.', 'Package commands|Package commands|CLI manages packages and updates.'],
['Codemode tool|codemode|Model scripts call tools or non-LLM models and expose selected output.', 'QuickJS capabilities|QuickJS sandbox|No direct Node/filesystem/network/timers are available.', 'searchTools|searchTools|BM25 ranking discovers callable tools.', 'models operations|models|Global lists and invokes image or classifier models.', 'Output bounds|16777216|Scripts fail after character or output-item limits.'],
],
[
['Context compaction|Compaction Reference|Summarizes old messages while retaining session entries.', 'Branch summarization|Branch summarization|Preserves relevant context when switching tree branches.', 'Compaction threshold|contextTokens >|Auto compaction triggers near contextWindow minus reserveTokens.', 'CompactionEntry|CompactionEntry|Persisted entry carries compacted context.', 'Extension summarization hooks|session_before_compact|Extensions can customize compaction and tree summaries.'],
['Configuration layering|user-level and project|Project settings load after trust and override user-level configuration.', 'Agent directory|PI_CODING_AGENT_DIR|User configuration defaults to ~/.pi/agent and can be relocated.', 'Project trust exception|sessionDir|Session directory is read before trust to locate sessions.'],
['Process isolation|isolated environment|Containers/VMs limit accessible resources.', 'Docker Sandboxes|Docker Sandboxes|Managed isolation can substitute host-held provider credentials through a proxy.', 'OpenShell|OpenShell|Sandbox policies control filesystem/process/network/credentials.', 'Gondolin|Gondolin extension|Host Pi delegates selected tools into a micro-VM.'],
['Custom provider extensions|provider extension|Adds auth, discovery or protocols beyond compatible static endpoints.', 'pi.registerProvider|pi.registerProvider|Factory registers native Provider or legacy ProviderConfig.', 'Native provider composition|Pi composes|models.json overrides layer above native providers.', 'refreshModels|refreshModels|Providers can discover and refresh models dynamically.'],
['Process markers|Process Marker|CLI/RPC mark child processes with AI_AGENT and PI_CODING_AGENT.', 'Shell session environment|Shell Tool Session Environment|Shell calls receive current session/model/reasoning variables.', 'PI_MODEL|PI_MODEL|Variable names the selected Pi model rather than upstream router decisions.'],
['Extensions runtime|Extensions|TypeScript modules add executable tools, commands, events and providers.', 'ExtensionAPI|ExtensionAPI|Factory receives the capability registration API.', 'jiti loading|jiti|Local TypeScript extensions load without separate compilation.', 'Runtime reload|Reload replaces|Reload replaces runtime and old state cannot be reused afterward.', 'Trusted in-process execution|same operating-system permissions|Extensions share process access to prompts, credentials and history.'],
['Agent loop|Agent loop|Streams assistant response, executes tools and records results for each turn.', 'Active branch context|active branch|Selected tree path supplies next request history.', 'Steering versus follow-up|Steering messages|Steering enters after current turn; follow-up waits for pending work.', 'Persistent JSONL sessions|JSONL|Entry IDs and parent links retain branches.', 'Context assembly|Context|System instructions, tools and skill descriptions accompany branch messages.'],
['Pi documentation entry|extensible AI agent|Docs introduce local multistep agent work.', 'Integration chooser|Automate or embed Pi|Print/JSON/RPC/SDK serve different integration needs.', 'Customization chooser|Customize Pi|Resources add prompts, instructions, behavior, UI and providers.'],
['JSONL event framing|strict JSONL framing|Records end only at LF, optionally preceded by CR.', 'Session header|Session header|JSON mode starts with session header; RPC does not.', 'Streaming reconstruction|Reconstruct streaming messages|Consumers reconstruct messages from deltas and authoritative completion.', 'Tool execution events|Tool execution events|Tool progress appears in the shared event stream.'],
['Named keybinding actions|named actions|User configuration maps action identifiers to keys.', 'keybindings.json|keybindings.json|Values replace defaults; empty arrays disable bindings.', 'Kitty modifier reporting|Kitty keyboard protocol|Super modifiers require terminal support.'],
['llama.cpp router|router server|Router discovers GGUF models and loads/unloads them on demand.', 'Jinja tool templates|--jinja|Compatible templates enable tool calling.', 'Manual local model loading|--no-models-autoload|Connection setup does not load models when autoload is disabled.', 'llama model management|/llama|Interactive command loads available local models.'],
['MCP integration|Model Context Protocol|Tools/resources connect via stdio or streamable HTTP.', 'Project MCP override|project entry without|Project entry can selectively override user server exposure and enablement.', 'MCP OAuth|Authenticate with OAuth|HTTP servers support configured OAuth.', 'Tool exposure|toolExposure|Configuration controls how tools are made available.', 'Trust-gated project servers|Project configuration is read|Project servers load only after trust.'],
['AgentMessage union|AgentMessage|Shared messages serve SDK/events/RPC/persisted entries.', 'Content blocks|Content blocks|Text, image, thinking and toolCall blocks carry typed content.', 'Opaque provider signatures|opaque|Replay metadata must be treated as opaque.', 'Usage accounting|reasoning|Reasoning tokens are already included in output.'],
['Model catalogue overlay|overlay newer catalog|Bundled models overlay newer pi.dev data with offline cache availability.', 'Authentication precedence|runtime --api-key|Runtime override, stored auth, model config, then ambient/env auth.', 'Model selection|Select a model|Picker filters models by usable auth.', 'Thinking capabilities|thinking level|Available levels are clamped to selected-model capabilities.'],
['Pi package resources|Pi packages|Extensions, skills, prompts and themes are shared as units.', 'Pinned package sources|Versioned npm|Versioned npm/git tags/commits remain pinned.', 'Trust-gated project packages|Project packages|Project packages install and load after trust.', 'pi manifest|pi manifest|Explicit manifest paths narrow resource discovery.'],
['Prompt templates|Prompt templates|Markdown files expand into reusable slash commands.', 'Argument substitution|Templates support|Positional/default/slice forms substitute shell-like arguments.', 'Input expansion|Pi expands|Expansion occurs before agent input and after raw extension input handling.'],
['Provider authentication|OAuth|Providers use subscription OAuth, API keys or cloud ambient credentials.', 'auth.json|auth.json|Stored credentials are private and not revoked by local logout.', 'Environment API keys|Use an API key|Environment variables provide nonpersistent credentials.', 'Ambient cloud credentials|ambient cloud credentials|Bedrock and Vertex AI can authenticate with ambient credentials.'],
['Managed Pi installation|installer pins|Installer pins all dependencies and updates through Pi.', 'Nix installation|Nix builds|Nix builds from source and uses profile upgrade for updates.', 'Working directory grouping|group saved sessions|Working folder controls resource discovery and session grouping.', 'Model/provider distinction|A model generates|Model generates responses; provider supplies model access.'],
['RPC prompt acceptance|success: true|Prompt response acknowledges acceptance, queueing or handling rather than completion.', 'Streaming queue disposition|streamingBehavior|Steer/followUp choose when prompts enter ongoing work.', 'Extension command handling|Extension commands|Commands execute immediately and manage their own interactions.', 'State commands|State|Protocol exposes session state and messages.', 'Session commands|Session|Protocol exposes tree/fork/clone/session controls.'],
['RPC extension dialogs|Dialog methods|select/confirm/input/editor wait for matching client responses.', 'UI notifications|Fire-and-forget methods|Notification/status/widget updates do not require responses.', 'RPC UI limitations|Limitations|Terminal-dependent UI methods are unavailable or degraded.', 'Dialog timeout|timeout field|Agent resolves unanswered dialogs with defaults at timeout.'],
['RPC subprocess|long-lived subprocess|JSON records control Pi across a process boundary.', 'RpcClient|RpcClient|Typed client starts Pi and correlates commands/events.', 'Command correlation|Correlate commands|Optional IDs correlate concurrent asynchronous responses.', 'Shared protocol record families|four record families|Commands, responses, session events and UI records have distinct purposes.'],
['createAgentSession|createAgentSession|Embeds Pi through direct TypeScript methods.', 'AgentSession|AgentSession|Owns conversation, models/tools, queue, compaction and extension runtime.', 'SessionManager authority|SessionManager is authoritative|Finalized model context is reconstructed from persisted entries.', 'In-memory session storage|SessionManager.inMemory|Host can opt out of session files.'],
],
[
['OS permission boundary|permissions of the account|Generated code runs with user-level access unless externally restricted.', 'Project trust|project trust|Controls resource loading but does not make generated actions safe.', 'Prompt injection|prompt injection|Files, outputs, instructions and responses can steer model behavior.', 'Process versus tool isolation|only its built-in tools|Tool-only isolation leaves host extensions outside the boundary.'],
['Session JSONL tree|id/parentId|Entries retain branch structure within one session file.', 'Session v3|Version 3|Current format renames hookMessage to custom.', 'SessionManager|SessionManager|API creates, persists and navigates the entry tree.', 'CompactionEntry|CompactionEntry|Summary entry contributes to reconstructed context.', 'Context building|Context Building|Active-tree entries reconstruct provider history.'],
['Session continuation|--continue|Continues the most recent current-directory session.', 'Tree navigation|/tree|Branches within a file without erasing abandoned paths.', 'Fork versus clone|/fork|Fork copies earlier history while clone copies the active branch.', 'Context management|Manage conversation context|Active branch and summaries determine sent history.'],
['Settings precedence|Project settings override|Project values override user values while resource lists combine.', 'Cache warming|cacheWarming|Eligible prompt caches warm when estimated avoided cost exceeds the threshold.', 'Thinking levels|defaultThinkingLevel|Settings provide global and per-model startup choices.', 'Queue delivery modes|steeringMode|Steering/follow-up delivery is all or one-at-a-time.'],
['Non-interactive shell|non-interactive shell|Each Bash command starts a separate noninteractive process.', 'shellPath|shellPath|Selects Bash executable.', 'shellCommandPrefix|shellCommandPrefix|Setup prefix runs before every built-in/user Bash command.', 'Alias expansion|expand_aliases|Explicitly enable and source Bash-compatible aliases.'],
['Agent Skills|Agent Skills specification|Skills provide reusable workflow instructions and supporting assets.', 'On-demand skill loading|full instructions only|Startup advertises metadata; model loads detailed instructions on demand.', 'Explicit skill command|/skill:name|Command forces skill loading with appended arguments.', 'Portable skill resources|relative paths|Supporting references resolve relative to skill directory.'],
['Slash command discovery|Type /|Terminal menu searches current built-in and loaded-resource commands.', 'Session commands|Sessions and context|Commands resume, branch, fork, clone, compact and import history.', 'Resource-added commands|Commands added by resources|Extensions/templates/skills contribute commands.'],
['Terminal extended-key protocols|extended-key protocols|Terminals distinguish modified Enter from plain Enter.', 'Kitty keyboard protocol|Kitty|Kitty supports required keyboard reporting directly.', 'Terminal capability overrides|Override detected capabilities|Configuration can compensate for incorrect image/color detection.', 'IME placement|IME|Terminal/IDE setup can affect candidate window positions.'],
['Termux Android|Termux|Android terminal supports text/file/shell tasks.', 'Termux clipboard|Termux:API|Optional API integrates Android text clipboard but no image paste.', 'Android shared storage|termux-setup-storage|Permission grants access to shared files with Termux process rights.'],
['System theme|system theme|Terminal foreground/background and ANSI palette determine adaptive colors.', 'Theme contrast|4.5:1|Body text maintains documented minimum WCAG contrast.', 'Theme switching|light/dark|Separate themes follow detected terminal appearance.', 'Custom themes|Create a custom theme|JSON palettes customize interactive UI and HTML exports.'],
['tmux extended keys|extended-keys on|tmux must forward modified keys distinctly.', 'CSI-u|extended-keys-format csi-u|Recommended for tmux 3.5+.', 'modifyOtherKeys|modifyOtherKeys|Older 3.2–3.4 use the supported xterm format.'],
['Terminal component system|pi-tui|Pi-tui supplies the component system for extension interfaces.', 'ctx.ui integration|ctx.ui|Use dialogs/widgets before custom renderers.', 'Column width helpers|visibleWidth|ANSI/wide-character output needs visible terminal column measurement.', 'Render scheduling|tui.requestRender|State changes invalidate cache and schedule a coalesced render.'],
['Interactive transcript|transcript|Shows prompts, responses, tools, results and errors.', 'Prompt attachments|To include files|File/image references become prompt content.', 'Steering input|message sent with|Enter guides the next response after current tools finish.', 'Follow-up input|Alt+Enter|Queued task waits for ongoing work to finish.'],
['Virtual models|virtual model|Selectable model routes each request to a physical model.', 'Selection versus dispatch|Pi keeps the two pairs apart|Session changes track selected model; responses track physical dispatched model.', 'Routed thinking|virtual thinking level|Router maps virtual level to a physical model/level.', 'Physical context limits|Compaction checks|Compaction checks request-routed model context capacity.'],
['Native Windows|native Windows process|Default Bash uses Git for Windows.', 'Optional PowerShell|powershell tool|Model tool can use native PowerShell; user exclamation commands keep Bash.', 'WSL environment|WSL|Uses Linux tools inside the distribution.'],
['Integration examples|Example code|Examples cover SDK, subprocess integration and extensions.', 'RpcClient example|rpc-client.ts|Typed subprocess example streams events and waits for settlement.', 'Chord facet plugin example|pi-example-plugin|Experimental plugin separates Session-worker and TUI facets.'],
['Permission gate example|permission-gate.ts|Extension confirms dangerous shell commands.', 'Protected path example|protected-paths.ts|Extension blocks writes to sensitive paths.', 'Dynamic tool example|dynamic-tools.ts|Registers tools after startup and at runtime.', 'Subagent extension example|subagent/|Delegates work with isolated contexts.', 'Plan-mode extension example|plan-mode/|Read-only analysis and progress tracking are extension features.'],
['DOOM terminal overlay|35 FPS|Overlay supports real-time game rendering.', 'doomgeneric WebAssembly|doomgeneric|Portable game compiled to WebAssembly.', 'Half-block rendering|half-block|24-bit foreground/background encode paired vertical pixels.'],
['Dynamic resource skill|resources_discover|Example skill is supplied dynamically through extension resource discovery.'],
['Dynamic repository summary template|resources_discover|Dynamically loaded template requests structure and build/test command summary.'],
['Plan-mode example|Read-only exploration|Extension disables write tools and filters Bash in exploration mode.', 'Bash allowlist|Bash allowlist|Only allowlisted read-only commands run during plan mode.', 'Plan progress markers|DONE:n|Explicit completion markers update a persistent progress widget.', 'Execution mode restoration|Full tool access restored|Execution mode restores tools and tracks planned steps.'],
['Subagent isolated processes|separate pi process|Each delegated agent runs in its own Pi process/context.', 'Parallel streaming|Parallel streaming|Parallel subagents stream updates concurrently.', 'Project-local agent trust|Project-local agents|Repository-controlled prompts require trust or confirmation.', 'Agent discovery|agents.ts|User-level definitions are loaded by default.'],
]
]

def norm(s):
    return re.sub('[^a-z0-9]', '_', s.lower())

coverage = {'token_usage': 'unknown: tools expose no agent input/output usage; zeros are schema placeholders, not zero consumption', 'files': [], 'failures': []}
results = []
for bi, specs in enumerate(rows):
    assert len(specs) == len(batches[bi])
    nodes, edges, index = [], [], {}
    for fi, (f, concepts) in enumerate(zip(batches[bi], specs)):
        text = Path(f).read_text()
        stem = norm(str(Path(f).relative_to(root).with_suffix('')))
        ids = []
        for item in concepts:
            label, anchor, description = item.split('|', 2)
            nid = stem + '_' + norm(label)
            # Location uses exact evidence term and line when present; absent terms retain the source heading.
            position = text.find(anchor)
            line = text[:position].count('\n') + 1 if position >= 0 else 1
            location = f'{Path(f).relative_to(root)}:{line} ({anchor if position >= 0 else text.splitlines()[0]})'
            node = {'id': nid, 'label': label, 'file_type': 'concept', 'source_file': f, 'source_location': location, 'source_url': None, 'captured_at': None, 'author': None, 'contributor': None, 'description': description}
            if label in ('Minimal extensible core', 'Ownership immutability', 'Dedicated OAuth state', 'Local-user trust boundary', 'Chord standalone boundary', 'Session-safe Git'):
                node['file_type'] = 'rationale'
                node['rationale'] = description
            nodes.append(node)
            ids.append(nid)
            index[(fi, label)] = nid
        for nid in ids[1:]:
            target = next(n for n in nodes if n['id'] == nid)
            edges.append({'source': ids[0], 'target': nid, 'relation': 'conceptually_related_to', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': f, 'source_location': target['source_location'], 'weight': 1.0})
        is_changelog = Path(f).name == 'CHANGELOG.md' and len(text) > 5000
        if is_changelog:
            depth = 'overview: recent release sections and heading inventory; no per-version historical audit'
        elif len(text) <= 2500:
            depth = 'full text'
        else:
            depth = 'static overview: opening content and section-heading inventory; selected mechanism paragraphs where read'
        coverage['files'].append({'source_file': f, 'batch': bi+1, 'reading_depth': depth, 'bytes': len(text.encode()), 'nodes': len(ids), 'gaps': [] if depth == 'full text' else ['Not a line-by-line audit; code blocks and later reference detail not exhaustively modeled.']})
    # Substantive cross-file connections: inferred similarity only where explicit citation is absent.
    bridges = {
      0: [(4,'Contributor approval',8,'Issue gate'),(4,'Contributor approval',12,'PR gate'),(15,'Release changelog audit',20,'Task completion prompt'),(7,'Issue analysis',17,'Issue investigation')],
      1: [(1,'Lockstep releases',0,'Controlled TUI testing'),(3,'Contribution gate',2,'Development invariants'),(4,'Pi agent harness',18,'Pi coding agent'),(7,'Stateful Agent',9,'Unified LLM API'),(10,'Replicated state plan',11,'Replicated state'),(11,'Replicated state',12,'Chord Delta'),(16,'QuickJS CodemodeSandbox',21,'Codemode tool'),(19,'CLI interface selection',20,'Command-line invocation')],
      2: [(0,'Context compaction',6,'Active branch context'),(1,'Configuration layering',14,'Trust-gated project packages'),(5,'Extensions runtime',3,'Custom provider extensions'),(8,'JSONL event framing',20,'Shared protocol record families'),(11,'Trust-gated project servers',1,'Configuration layering'),(12,'AgentMessage union',8,'Streaming reconstruction'),(19,'RPC extension dialogs',20,'RPC subprocess'),(21,'SessionManager authority',6,'Persistent JSONL sessions'),(13,'Model selection',16,'Provider authentication')],
      3: [(0,'Project trust',20,'Plan-mode example'),(1,'Session JSONL tree',2,'Tree navigation'),(3,'Settings precedence',4,'shellCommandPrefix'),(6,'Resource-added commands',5,'Explicit skill command'),(7,'Terminal extended-key protocols',10,'tmux extended keys'),(9,'System theme',11,'Terminal component system'),(12,'Steering input',13,'Selection versus dispatch'),(15,'Integration examples',16,'Dynamic tool example'),(16,'Subagent extension example',21,'Subagent isolated processes'),(18,'Dynamic resource skill',19,'Dynamic repository summary template')]
    }[bi]
    for a, la, b, lb in bridges:
        source, target = index[(a, la)], index[(b, lb)]
        n = next(n for n in nodes if n['id'] == source)
        edges.append({'source': source, 'target': target, 'relation': 'semantically_similar_to' if (bi,a,b) in ((1,4,18),(1,10,11),(1,16,21)) else 'conceptually_related_to', 'confidence': 'INFERRED', 'confidence_score': 0.85, 'source_file': n['source_file'], 'source_location': n['source_location'], 'weight': 1.0})
    fragment = {'nodes': nodes, 'edges': edges, 'hyperedges': [], 'input_tokens': 0, 'output_tokens': 0}
    assert len({n['id'] for n in nodes}) == len(nodes)
    assert all(e['source'] in {n['id'] for n in nodes} and e['target'] in {n['id'] for n in nodes} for e in edges)
    path = out / f'.graphify_chunk_{bi+1:02d}.json'
    path.write_text(json.dumps(fragment, ensure_ascii=False, indent=2))
    results.append({'path': str(path), 'nodes': len(nodes), 'edges': len(edges)})
(out / 'semantic-coverage-a.json').write_text(json.dumps(coverage, ensure_ascii=False, indent=2))
print(json.dumps({'outputs': results, 'coverage': str(out/'semantic-coverage-a.json'), 'failures': []}))
